### ISSUE TITLE
Missing migration

### ISSUE THREAD

**Issue by joaomarcoscrs** [fabiocaccamo/django-extra-settings#23]
**Python version**
3.9.10

**Django version**
4.0.4

**Package version**
0.3.2

**Current behavior (bug description)**
Every time I start my django app, it acuses some changes that were not reflected in migrations.

The message displayed:

```
Your models in app(s): 'extra_settings' have changes that are not yet reflected in a migration, and so won't be applied.
 Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```

**Expected behavior**
Not to acuse missing migrations.

**Comment by joaomarcoscrs** [comment]
I've made a PR to fix the issue: https://github.com/fabiocaccamo/django-extra-settings/pull/24

**Comment by fabiocaccamo** [comment]
@joaomarcoscrs this is not a bug, you have this issue because probably you have set `DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'` in your settings and this app uses the default setting.
To avoid this problem, the solution is not to add a new migration, but adding `default_auto_field = "django.db.models.AutoField"` to the app config.
